# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flownews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pass_type', models.CharField(max_length=20)),
                ('pass_title', models.CharField(max_length=100)),
                ('pass_summery', models.CharField(max_length=500)),
                ('pass_img', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('index_pinyin', models.SlugField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='uploads/product/')),
                ('product_summery', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('product_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('is_subclass', models.BooleanField()),
                ('img', models.ImageField(upload_to='uploads/productCategory/')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summery', models.CharField(max_length=500)),
                ('set_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Latest')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suiyuan.Passage')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suiyuan.ProductCategory'),
        ),
        migrations.AddField(
            model_name='passage',
            name='pass_content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suiyuan.PassageContent'),
        ),
        migrations.AddField(
            model_name='hotproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suiyuan.Product'),
        ),
        migrations.AddField(
            model_name='flownews',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suiyuan.Passage'),
        ),
    ]
